apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
  labels:
    app: portal-noticias
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias
  template:
    metadata:
      labels:
        app: portal-noticias
    spec:
      containers:
      - name: portal-noticias
        image: aluracursos/portal-noticias:1
        ports:
        - containerPort: 80